---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/users/{user_id}/posts":
    parameters:
      - name: user_id
        in: path
        description: user_id
        required: true
        schema:
          type: string
    get:
      summary: list posts
      responses:
        "200":
          description: successful
  "/api/users/{user_id}/posts/{id}":
    parameters:
      - name: user_id
        in: path
        description: user_id
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
    get:
      summary: show post
      responses:
        "200":
          description: successful
  "/api/users":
    get:
      summary: list users
      responses:
        "200":
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
                    bio:
                      type: string
                    posts_counter:
                      type: integer
                required:
                  - id
                  - name
                  - email
                  - bio
                  - posts_counter
  "/api/users/{id}":
    get:
      summary: show user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  bio:
                    type: string
                  posts_counter:
                    type: integer
                required:
                  - id
                  - name
                  - email
                  - bio
                  - posts_counter
servers:
  - url: http://{defaultHost}
    variables:
      defaultHost:
        default: localhost:3000
