---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
                    bio:
                      type: string
                    posts_counter:
                      type: integer
                required:
                - id
                - name
                - email
                - bio
                - posts_counter
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
